/* 节点文字为阅读概括；page 指用户所提供 PDF 的页序。 */
window.LIFE_MAP=(()=>{
const C={nature:'#83cfbd',people:'#85b9d0',self:'#b9a6d8',tools:'#dcc498'};
const report={kind:'report',label:'2025 年讲座报道',url:'https://heshan.snnu.edu.cn/info/1041/8388.htm'};
const nodes={};
const add=(id,title,subtitle,summary,page,color,extra={})=>nodes[id]={id,title,subtitle,summary,page,color,children:[],scales:['earth','society','individual'],...extra};
add('root','生命实在','历史的起点，也是叙事的对象','王利华把自然生物、社会文化与个体生活放回同一个人的生命过程。事件、制度和观念由此联系到人的需求、实践、体验与意义。整张地图围绕这项初步研究构想展开。',12,C.tools,{quote:'“生命实在”是最根本的历史实在。',quotePage:12,question:'一个历史事件，怎样进入具体的人所经历的生命过程？',lenses:{all:'三重属性回答“人是什么”，三维时轴回答“在什么时间尺度观察”，四重关系回答“追踪哪些联系”。它们在同一生命过程中相互关联。',earth:'把人的身体、需求和生存限制放回地球生命演化与生态系统之中。',society:'追踪生产、制度、文化与工具怎样建造人的生活世界。',individual:'回到一个人的经历、选择、情感和意义，让宏观历史进入具体生命。'}});
add('nature','人与自然','生命的基底','人始终属于自然，生命依赖空气、水、食物以及适宜的生态条件。人与自然的联系既规定生活的边界，也在人类的持续实践中发生改变。',18,C.nature,{children:['needs','ecology','coevolution'],question:'人怎样维持生命，又怎样改变维持生命的自然条件？',scales:['earth','society'],lenses:{earth:'自然生命与地球生态系统具有漫长的形成过程，是人类历史的宏观基底。',society:'生产与生计方式改变资源利用，也改变人与自然交往的范围和强度。',individual:'人的呼吸、饮食、身体感受与环境耐受范围，使生态联系进入日常生活。'}});
add('people','人与人','生命的关系网络','家庭、社区、劳动与政治经济制度为生命活动提供机会、保障和限制。作者将社会关系视为理解历史变化的核心维度，并追问这些关系的矛盾、失衡与和解。',18,C.people,{children:['production','organization','culture'],question:'谁获得生活的保障与机会，谁承受关系中的压力？',scales:['society','individual'],lenses:{earth:'人们共同面对自然条件，但获得资源和承担风险的机会并不相同。',society:'经济方式、社会组织与文化传统共同塑造生命活动的条件。',individual:'一个人通过家庭、朋友、工作与公共生活经历这些社会联系。'}});
add('self','人与自我','生命的体验与意义','个人的情感、认同、追求与选择构成生命史的具体维度。作者希望把自我迷失和意义消解转化为历史问题，考察它们如何在特定自然与社会文化环境中形成。',18,C.self,{children:['experience','agency','meaning'],question:'处在这个生活世界中的人，怎样理解并完成自己？',scales:['individual','society'],lenses:{earth:'每个个体的体验都以具身的生命为前提，身体具有自然限制。',society:'文化、教育、家庭与制度影响人怎样认识自己、追求什么。',individual:'喜怒哀乐、人生际遇与自主选择，使个体生活无法被宏观事件完全替代。'}});
add('tools','人与技术','贯穿前三重关系的中介','工具延伸人的能力，技术变迁也改变人的环境、社会联系和自我体验。作者将人与自身创造物的关系提升为生命史问题，关注人如何使用技术，又如何受到技术塑造。',18,C.tools,{children:['making','mediation','autonomy'],question:'能力交给工具之后，人怎样继续掌握自己的生命过程？',lenses:{earth:'工具参与人对环境的利用与改造，并改变物质、能量和信息的联系。',society:'从手工工具到自动化生产，技术变迁重塑生产方式与社会组织。',individual:'智能工具提高能力的同时，也使记忆、注意力和判断如何被分配成为问题。'}});
add('needs','生命需求','吃、喝、住、穿与生存条件','主文本借助马克思的启示，把普通人的生命需求与物质生活生产放在历史起点。生理需要有自然规定性，满足需要的方式则具有社会文化历史。',9,C.nature,{scales:['earth','individual']});
add('ecology','生态基底','人赖以存活的生命系统','人的身体与生理需要植根于漫长的地球生命史。作者要求研究者认识人对生态条件的依赖，并把资源边界和环境耐受范围带入历史观察。',13,C.nature,{scales:['earth']});
add('coevolution','协同演化','自然与社会相互塑造','三维时轴既有层级制约，也有局间交互：自然规定资源边界，社会提供活动条件，个人汇聚的行动又可能推动社会与生态变化。',17,C.nature,{scales:['earth','society']});
add('production','物质生活生产','维持生命的劳动实践','生产活动使人的自然需求进入社会历史。作者关注不同历史条件下，人如何生产生活所需，以及生产方式的变化怎样影响存续与意义追求。',9,C.people,{scales:['society','earth']});
add('organization','社会组织','家庭、社区、国家与世界','生命活动在多层关系中展开。关系网络提供保障，也形成约束；自然条件、政治制度与经济方式共同影响这些关系的变化。',14,C.people,{scales:['society','individual']});
add('culture','文化与价值','生活方式的先在框架','文化传统影响人怎样认知生命、理解意义并选择行动。不同价值观引导不同生命实践，社会文化属性也在历史中持续变化。',14,C.people,{scales:['society','individual'],links:[{view:'sources',id:'shengsheng',text:'连接到“生生之道”'},{view:'sources',id:'marx',text:'连接到马克思的启示'}]});
add('experience','生命体验','具体人生中的感受与遭遇','个体经历、情感与人生目标各不相同。生命史希望保留历史过程中的体验主体，让个人内在世界进入解释。',14,C.self,{scales:['individual']});
add('agency','能动与创造','生命过程中的选择','个人具有自主选择与创造性，同时生活在自然和社会文化条件中。作者把这种条件中的行动看作生命实在动态生成的一部分。',13,C.self,{scales:['individual','society']});
add('meaning','生命意义','什么是值得追求的生活','意义追求与生活目标引导个体行动，涉及能力、人格、精神与自我实现。主文本把促进“完整的人”的发展作为研究的价值方向。',15,C.self,{scales:['individual'],links:[{view:'attributes',id:'complete',text:'继续阅读“完整的人”'}]});
add('making','作物制器','能力的延伸与文明变迁','从工具制作到机械和自动化，人的生活世界不断由技术实践重新塑造。作者要求技术史进入对生命存续方式的考察。',18,C.tools,{scales:['society','earth']});
add('mediation','技术中介','物质、能量、信息的联系','技术介入人对环境的作用、人与人的组织以及个体体验。这种中介地位解释了作者为何把技术关系纳入原有三重关系。',18,C.tools,{links:[{view:'systems',id:'support',text:'连接到生命支撑系统'}]});
add('autonomy','主体与工具','便利、依赖与自我掌握','结尾中，作者描述自己使用多个智能体开展研究与制作，也写下信息推送和碎片化时间对沉思的干扰。技术能力与主体性由此成为同一段生活中的张力。',19,C.tools,{quote:'自己已经被先进的通讯工具技术剥夺了沉思的自由和能力。',quotePage:19,question:'使用工具的便利，怎样与沉思和自主判断共存？',scales:['individual','society']});
add('biological','自然生物属性','人的物质基础','呼吸、进食、睡眠、繁殖以及对环境因素的感受与耐受，都具有自然规定性。人的生物属性同时受到饮食、栖居、医疗等社会生活方式的影响。',13,C.nature,{children:['needs','ecology','body'],scales:['earth','individual']});
add('sociocultural','社会文化属性','人的关系网络','人生活在特定制度、经济结构、社会关系、文化传统和价值观念中。社会文化既规定生活方式，也在人类的历史实践中被改变。',14,C.people,{children:['organization','culture','production'],scales:['society']});
add('personal','个体生活属性','人的经验主体','每个人都有独特经历、情感体验、意义追求与生活目标。个体的选择具有创造性，也受自然和社会环境影响。',14,C.self,{children:['experience','agency','meaning'],scales:['individual']});
add('body','具身的生命','身体、感知与自然限制','作者提醒我们，自然生物属性既不能被忽略，也不能被简化。身体、生理和基因是生命基础，环境与社会实践则影响它们在具体生活中的表现。',15,C.nature,{scales:['earth','individual']});
add('complete','完整的人','自然、社会与个体的协调发展','作者以“完整的人”表达研究的价值方向：自然、社会与个体三重属性相互贯通，生理、心理、情感、理性、思想与行动得到协调发展。',15,C.tools,{quote:'“完整的人”，在历史中生成。',quotePage:18,links:[{view:'relations',id:'self',text:'回到人与自我的关系'}]});
add('shengsheng','生生之道','本土思想文化根基','作者从中国传统思想中提取整体性、连续性、创造性与价值性，关注生命共生、延续和创进，将其转化为历史思考的思想资源。',7,C.nature,{children:['holism','continuity','creation','value'],question:'怎样把生命关怀转化为能够展开历史研究的问题？'});
add('marx','马克思的启示','生命需要、实践与关系','作者从“有生命的个人”和物质生活生产出发，连接人与自然、人与人的两种基本关系，并以人的自由与完整发展作为思想指向。',9,C.people,{children:['firstpremise','practice','reconciliation'],question:'从有生命的个人出发，制度与事件会显露哪些新的联系？'});
add('civilization','生态文明','研究的价值方向','主文本以生态文明建设思想为价值遵循，将人与自然的和谐共生、生命共同体与历史根源的探究联系起来。',9,C.tools,{children:['community','harmony','historicalroots'],scales:['earth','society']});
add('dialogues','跨学科对话','以不同视野照见生命','医疗社会史、日常生活史、环境史、大史、深史、行星史等提供不同尺度与证据。作者同时指出各自局限，希望在具体问题中形成综合。',10,C.self,{children:['lifehistory','environment','bighistory','deephistory'],question:'扩大时间尺度之后，怎样仍然保留个体体验与文献证据？'});
add('holism','整体性','相互联系的生命','在作者对“生生”思想的提炼中，个体生命与不同生命形式构成相互联系、彼此影响的整体。',8,C.nature);
add('continuity','连续性','生命的流动与延续','生命既有个体从出生到死亡的过程，也有生命系统持续演化的过程。作者强调个人与更大生命世界之间的联系。',8,C.nature);
add('creation','创造性','延续中的创进','作者将生命过程理解为不断创造新形式、结构与可能性的展开，并关注人类实践的主动性。',8,C.nature);
add('value','价值性','生命关怀与伦理方向','生命本身具有价值。作者将尊重、理解和守护生命转化为历史研究的价值方向，同时承认传统思想中的等级与压抑需要反思。',8,C.nature);
add('firstpremise','有生命的个人','历史的第一个前提','主文本借《德意志意识形态》强调人的生命存在及其生理需求，进而将物质生活的生产视为生命存续和历史创造的前提。',9,C.people,{scales:['individual','society']});
add('practice','生命实践','主客观统一的展开','生命实在包含客观的自然与社会条件，也包含个人的主观能动性。作者将历史理解为生命实践持续生成的过程。',12,C.people);
add('reconciliation','双重和解','人与自然、人与人','作者借助马克思对异化的批判，把人与自然及人与人的关系同时放进历史考察，追问矛盾、断裂与和解的过程。',9,C.people,{scales:['earth','society']});
add('community','生命共同体','人、其他生命与生态系统','主文本将人与生物及山水林田湖草沙之间的联系作为生态文明思想资源，强调共同存续的自然基础。',9,C.tools,{scales:['earth','society']});
add('harmony','和谐共生','利用、保护与生活实践','尊重自然、顺应自然与保护自然构成本文的价值导向。作者要求透过历史过程认识人与生态系统的联系。',9,C.tools,{scales:['earth','society']});
add('historicalroots','历史根源','现实困境怎样形成','作者主张把生态危机、社会冲突与个体困境放进时间纵深，揭示关系失衡的形成过程。',18,C.tools);
add('lifehistory','生命史与生活史','体验、健康与日常生活','主文本回顾医疗社会史与日常生活史的生命关怀，借助它们保留个体体验和具体生活情态。',6,C.self,{scales:['individual','society']});
add('environment','环境史与行星史','自然进入历史','环境史提供人与自然交互作用的观察，行星史进一步将人类生命活动联系到地球系统。作者也提醒，个体体验和文化能动性需要保留。',10,C.self,{scales:['earth','society'],extraSource:{kind:'dialogue',label:'2023 年作者对话',url:'https://news.nankai.edu.cn/mtnk/system/2023/12/09/030059282.shtml'}});
add('bighistory','大史','宏观的时间框架','大史将人类历史放入宇宙、地球与生命演化的宏观框架。作者吸收这一尺度，同时关注宏观叙事如何容纳具体人的生活。',11,C.self,{scales:['earth']});
add('deephistory','深史','生物性与文化性的共同演化','深史跨越历史与史前的界限，综合考古学、遗传学、人类学等知识。本文借此观察生物属性与文化行为持续交互的过程。',11,C.self,{scales:['earth','society']});
add('support','生命支撑系统','怎样获得生存所需','从食物、能量、空气、水等生命条件出发，追踪人们如何获得并维持生存所需。这一系统连接自然条件、生产实践与社会安排。',6,C.nature,{children:['foodwater','flows','livelihood'],source:report,question:'哪些自然条件和社会实践，共同支撑人的日常生活？',scales:['earth','society']});
add('defense','生命防卫系统','怎样保护生命与健康','医疗、公共卫生及防疫研究直接关乎生命、健康与安全。作者把这一研究方向纳入生命史的整体构想。',6,C.people,{children:['medicine','publichealth','safety'],source:report,question:'面对疾病和风险，人们建立过怎样的生命保护方式？',scales:['society','individual']});
add('cognition','生态认知系统','怎样认识与解释环境','人们用知识、观念和经验认识周遭自然条件，并据此组织实践。认知本身具有历史，影响人如何理解生命、资源与环境。',6,C.self,{children:['knowledge','resources','perception'],source:report,question:'什么被人们认作资源、风险或可利用的环境条件？',scales:['society','individual']});
add('coorganization','生态—社会互组织','自然条件与社会安排','研究人们怎样把自然条件与社会组织联系起来，观察生态系统和社会系统如何在历史实践中相互作用。',6,C.tools,{children:['settlement','institutions','coordination'],source:report,question:'社会安排怎样因应自然条件，又怎样改变这些条件？',scales:['earth','society']});
add('foodwater','食物与水','生命条件的取得','主文本把食物、空气、水和其他存活条件归入生命支撑系统。研究由人的需求展开，追踪其取得与维持的过程。',6,C.nature,{scales:['earth','individual']});
add('flows','物质、能量、信息','理解人与自然联系的维度','2025 年讲座报道以物质、能量和信息作为理解人与自然联系的底层维度，并连接具体时期与地区的研究问题。',null,C.nature,{source:report,scales:['earth','society']});
add('livelihood','生计实践','养活生命的劳动','主文本以农业劳动为生命活动，强调人与天地生物的合作，以及物质、能量和信息的交往。',6,C.nature,{scales:['society','earth']});
add('medicine','医疗与身体','生命保护的研究入口','医疗社会史直接关注生命、身体、健康与安全，为本文的生命史构想提供重要支撑。',6,C.people,{scales:['individual','society']});
add('publichealth','公共卫生与防疫','群体生活中的保护','主文本回顾生命史研究对群体健康观念、公共卫生防疫以及社会文化和自然生态互动的关注。',6,C.people,{scales:['society','individual']});
add('safety','健康与安全','生命关怀的具体对象','健康与安全把历史制度、知识和实践联系到人的生命状态。本文要求它们与社会、自然和个体体验一起考察。',6,C.people,{scales:['individual','society']});
add('knowledge','知识与观念','人如何认识自然条件','主文本提出，人运用知识与多种方式组织周遭自然因素，建立生态认知系统。其具体形成过程需要历史研究展开。',6,C.self,{scales:['society']});
add('resources','资源认识','条件怎样进入生活实践','从生命需要出发，自然条件通过认知与利用进入社会实践。这里作为生态认知的阅读路径，提示需要追踪具体时地中的资源认识。',6,C.self,{scales:['society','earth']});
add('perception','经验与感知','生活世界中的认知','人的生态认识发生在具体生活世界里。主文本强调自然、社会与个人的联系，为追踪经验、感知和认知提供整体观察。',14,C.self,{scales:['individual','society']});
add('settlement','生活空间','自然条件与日常生活','作者强调人的生活世界持续受到自然与社会条件影响。聚居、生活和栖居方式可以成为观察两类系统联系的入口。',13,C.tools,{scales:['society','earth']});
add('institutions','社会安排','关系、制度与实践','政治制度、经济方式与社会结构共同规约生命活动，它们的形成和变化是生态—社会关系的研究对象。',14,C.tools,{scales:['society']});
add('coordination','因应与协同','在互动中考察历史','2025 年讲座报道强调自然秩序与社会秩序之间的因应和协同，关注生态系统与社会系统的历史互动。',null,C.tools,{source:report,scales:['earth','society']});
add('care','生命关怀','思想资源之间的共同线索','主文本从本土生生思想、马克思的人与自然关系理论、生态文明思想及多学科对话中提取资源。作者希望以生命关怀为共同方向，同时吸收不同研究路径的具体成果。',7,C.tools,{question:'不同思想资源如何帮助我们提出更具体的历史问题？'});
add('systemroot','生命系统','从思想宗旨进入研究对象','主文本回顾生命支撑、生命防卫、生态认知与生态—社会互组织的系统思路。2025 年讲座报道将它们组织为四条研究路径。这一层可用来寻找生命条件、知识、保护和社会安排之间的联系。',6,C.tools,{source:report,question:'从哪一个具体过程，可以开始追踪生命与环境的历史联系？'});
const views={relations:{label:'四重基本关系',ids:['nature','people','self','tools'],root:'生命实在',subtitle:'自然 · 社会 · 个体',intro:'历史的起点',index:'01'},attributes:{label:'人类生命的三重属性',ids:['biological','sociocultural','personal'],root:'完整的人',subtitle:'自然 · 社会 · 个体',intro:'同一个人的三个维度',rootId:'complete',index:'02'},sources:{label:'学术宗旨与思想资源',ids:['shengsheng','marx','civilization','dialogues'],root:'生命关怀',rootId:'care',subtitle:'资源 · 对话 · 继承',intro:'一套框架怎样形成',index:'03'},systems:{label:'环境史研究的四个系统',ids:['support','defense','cognition','coorganization'],root:'生命系统',rootId:'systemroot',subtitle:'支撑 · 防卫 · 组织 · 认知',intro:'进入可研究的过程',index:'04'}};
const lenses={all:{label:'全部尺度',description:'三种时间相互嵌套，也彼此改变'},earth:{label:'地球生命时间',description:'自然演化与生态基底 · 主文本第 16—17 页'},society:{label:'社会生命时间',description:'生产、制度与文化创进 · 主文本第 16—17 页'},individual:{label:'个体生命时间',description:'经历、选择与生命体验 · 主文本第 17 页'}};
const tour=[{view:'relations',id:'root',lens:'all',title:'从有生命的人出发'},{view:'attributes',id:'biological',lens:'earth',title:'先看人的自然生物基础'},{view:'attributes',id:'sociocultural',lens:'society',title:'生活世界怎样被社会建造'},{view:'attributes',id:'personal',lens:'individual',title:'把具体的体验与选择带回来'},{view:'relations',id:'tools',lens:'all',title:'技术怎样贯穿三重关系'},{view:'sources',id:'shengsheng',lens:'all',title:'追踪框架的思想资源'},{view:'systems',id:'support',lens:'society',title:'从生命关怀进入具体研究'}];
return {nodes,views,lenses,tour,colors:C};
})();
